### ISSUE TITLE
va_list for callvoidmethodv

### ISSUE THREAD

**Issue by cjc-github** [chame1eon/jnitrace-engine#19]
Hi,
JNItrace is a great tool, but I have a question?
I want to get the concreate the value of va_list in callvoidmethodv。
for example,CallStaticVoidMethodV(jclass clazz, jmethodID methodID, va_list args).I'm sure that  the va_list only one parameters:String, now I should get the string value?

Help! ! !

**Comment by chame1eon** [comment]
Hi,

Thanks very much :). I am glad you find it useful.

Please can you send me some example code/command with what you are trying? I can then try to help with a solution.

Thanks

**Comment by cjc-github** [comment]
![选区_200](https://user-images.githubusercontent.com/49013706/203885974-84c474ca-7235-4daa-a4cd-517262de62c4.jpg)



I using jnitrace to trace the native code , it is work, And i just focus on Cal\*Method\* ,so I want to using jnitrace-engine or frida script to finish it. I want to know that how to obtain parameter address in va_lists. for example, 0x99 { +4923243234423}. it need to calculate the offset or base addr? How did you get this address?

**Comment by cjc-github** [comment]
test apk is testapk.zip, next is Snippet of script code.
[testapk.zip](https://github.com/chame1eon/jnitrace-engine/files/10088243/testapk.zip)

Now,I can get the call\*Method\* the className and methodId from args[1] and args[2]。so I want to the get the va_list information args[3].

NativeType Call<type>MethodV(JNIEnv *env, jobject obj, jmethodID methodID, va_list args);

**Comment by cjc-github** [comment]
try using Java.vm.getEnv().getStringUtfChars(args[3].add(0).readPointer()).readUtf8String(); can get the va_list the first parameters, but the address is not match the previous using（for example, picture in jnitrace ,0x99 for {+4923243234423} ）.Does this mean that offset addr or base addr needs to be calculated .

**Comment by chame1eon** [comment]
Thanks. I think I see what you mean. So the 0x99 is not an address it is a unique value generated by the JNI runtime to identify that object reference. Unfortunately it means you cannot do anything with it using JNI trace, other than tracking uses of that value (example 0x99) in other places.

Does that help or am I misunderstanding?

**Comment by cjc-github** [comment]
![test1](https://user-images.githubusercontent.com/49013706/204700016-a76617b8-9a13-4c43-bbb7-009685dc3bae.jpg)

Yeah, that's just what i need, I want to tracking uses of the value (example 0x99).For this picture,I tracking the JNI Function (example 1->2),so i want to know the CallVoidMethodV the 0x99 how to get? Thanks .

**Comment by chame1eon** [comment]
Great, thanks, now I understand. So you will need to write a jnitrace-engine script to do it. There is an example in the README of this project, but the basics will look like this for your example screenshot.

import { JNIInterceptor } from "jnitrace-engine";

// Attach to the JNI FindClass method
JNIInterceptor.attach("CallVoidMethodV", {
    onEnter(args) {
        // called whenever the CallVoidMethodV is about to be called
        console.log("CallVoidMethodV method called");
        this.jstring_ref = args[4].toInt32();
    }
});

The va_arg values are stored in the same array as the other args but offset by 1 to allow the actual va_arg address to be available too.

hope that helps.

**Comment by cjc-github** [comment]
Yes,that what I want,I will try it .Thanks a lot.
