### ISSUE TITLE
How to I retrieve the original pointer address of an argument?

### ISSUE THREAD

**Issue by Ayrx** [chame1eon/jnitrace-engine#2]
The callback for attaching to a JNI method is:

```
JNIInterceptor.attach("XXX", {
    onEnter(args) {
        //do stuff
    },
    onLeave(retval) {
        //do stuff
    }
});
```

From what I understand (I _might_ be wrong) the `NativePointer` address of an element of `args` is the address to the trampoline function and not the original JNI function. In other words `console.log(args[0])` does not show what I expect while `console.log(args[0].readPointer()` does. **How do I find the address of the `NativePointer` to the original JNI function and not the intercepted one?**

For context I am attaching to `RegisterNatives` and I want to dump out the address of the `methods` argument to it. I am not seeing the expected pointer addresses even after accounting for ASLR.

**Comment by chame1eon** [comment]
Hi,

I am not surely I fully understand the issue but I have tired to answer it as best I can, if I have misunderstood please let me know.

I wrote this sample script to test some of the issues you highlighted. I could not find anything wrong but hopefully this will explain it a bit better.

import { JNIInterceptor } from "jnitrace-engine"

```typescript
JNIInterceptor.attach("RegisterNatives", {
    onEnter(args) {
        const jniEnv = args[0] as NativePointer;
        console.log("JNIEnv", jniEnv.readPointer());
        const RegisterNatives = jniEnv.readPointer().add(215 * Process.pointerSize).readPointer()
        console.log("Table:", RegisterNatives, "===", "Actual:", this.jniAddress);

        const methods : NativePointer = args[2] as NativePointer;
        const libBase = Module.getBaseAddress("libnative-lib.so");

        console.log("Method Address:", methods.sub(libBase));
    }
});
```

The `NativePointer` in `args[0]` will be exactly the same as the one that is used by the runtime to do the JNI call. On library start up all entry points to the library are caught and a fake JNIEnv* is provided, that fake `JNIEnv*` has exactly the same structure as the real one it just exist in a different memory location. Whenever the library wants to use a JNI function the call is intercepted and the original `JNIEnv*` is replaced at `args[0]` else the runtime will crash when it detects a fake `JNIEnv*`. The JNIInterceptor will see the arguments as the runtime will see them, in other words the replacement of the correct `JNIEnv*` happens before the onEnter callback.

Regarding the `RegisterNatives` `methods` arguments, I found it was working as I expected in my test library. As you can see in the example code I grab `args[2]` and subtract the base address from it. I took the resulting value and checked it in a dissembler and it took me to the method array in memory.

**Comment by Ayrx** [comment]
Ah you are right of course! The binary I was testing against was copying the `methods` array to the local stack frame before passing it to `RegisterNatives` which explained my initial confusion. Thanks for the reply!
